/* AUTOGENERATED DO NOT EDIT */
#include <linux/bpf.h>
#include <stddef.h>
#include <stdint.h>

#include "tbpf.h"

size_t bpf_insn_prog_parser_cnt = 2;

struct bpf_insn bpf_insn_prog_parser[] = {
	{
		.code    = 0x61,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_1,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x95,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}};


struct tbpf_reloc bpf_reloc_prog_parser[] = {
	{
		.name = NULL,
		.type = 0,
		.offset = 0
	}};

size_t bpf_insn_prog_verdict_cnt = 36;

struct bpf_insn bpf_insn_prog_verdict[] = {
	{
		.code    = 0xbf,
		.dst_reg = BPF_REG_6,
		.src_reg = BPF_REG_1,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x61,
		.dst_reg = BPF_REG_3,
		.src_reg = BPF_REG_6,
		.off     = 132,
		.imm     = 0	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 2660	/**/
	}, {
		.code    = 0x6b,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -4,
		.imm     = 0	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 622883954	/**/
	}, {
		.code    = 0x63,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -8,
		.imm     = 0	/**/
	}, {
		.code    = 0x18,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 1633906508	/**/
	}, {
		.code    = 0x0,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 1867522156	/**/
	}, {
		.code    = 0x7b,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -16,
		.imm     = 0	/**/
	}, {
		.code    = 0x18,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 544502383	/**/
	}, {
		.code    = 0x0,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 539780133	/**/
	}, {
		.code    = 0x7b,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -24,
		.imm     = 0	/**/
	}, {
		.code    = 0x18,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 1869440338	/**/
	}, {
		.code    = 0x0,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 1344300404	/**/
	}, {
		.code    = 0x7b,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -32,
		.imm     = 0	/**/
	}, {
		.code    = 0x18,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = -65536	/**/
	}, {
		.code    = 0x0,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x5f,
		.dst_reg = BPF_REG_3,
		.src_reg = BPF_REG_1,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x73,
		.dst_reg = BPF_REG_10,
		.src_reg = BPF_REG_1,
		.off     = -2,
		.imm     = 0	/**/
	}, {
		.code    = 0xdc,
		.dst_reg = BPF_REG_3,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 32	/**/
	}, {
		.code    = 0x61,
		.dst_reg = BPF_REG_4,
		.src_reg = BPF_REG_6,
		.off     = 136,
		.imm     = 0	/**/
	}, {
		.code    = 0xbf,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_10,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x7,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = -32	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_2,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 31	/**/
	}, {
		.code    = 0x85,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 6	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_3,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 1	/**/
	}, {
		.code    = 0x61,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_6,
		.off     = 136,
		.imm     = 0	/**/
	}, {
		.code    = 0x15,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_0,
		.off     = 1,
		.imm     = 50000	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_3,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0xbf,
		.dst_reg = BPF_REG_1,
		.src_reg = BPF_REG_6,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x18,
		.dst_reg = BPF_REG_2,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/* relocation for sock_map */
	}, {
		.code    = 0x0,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0xb7,
		.dst_reg = BPF_REG_4,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}, {
		.code    = 0x85,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 52	/**/
	}, {
		.code    = 0x95,
		.dst_reg = BPF_REG_0,
		.src_reg = BPF_REG_0,
		.off     = 0,
		.imm     = 0	/**/
	}};


struct tbpf_reloc bpf_reloc_prog_verdict[] = {
	{
		.name = "sock_map",
		.type = 1,
		.offset = 31
	}, {
		.name = NULL,
		.type = 0,
		.offset = 0
	}};

